;             
CREATE USER IF NOT EXISTS "SA" SALT '74bd85414411db2c' HASH '5678144032b65b581d1f72914c8997334b9dca8ff5880594a7ec3dd3c1f65b8a' ADMIN;         
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A7A91054_6B19_4EC5_8EA2_269793E320D3" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_3D52CACA_5642_4173_A252_ACDE3614828B" START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_E73589DB_09EF_41F0_830D_4F40457B04CA" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_ED57FF39_C934_45C7_A0A7_AFF9F28A7C42" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_49DFB9D7_BF09_4F8E_AE8F_A440A2042A8D" START WITH 4 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DE6CA346_FA89_4A07_8AE5_14FD560FECD1" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6EBD83B7_3312_4CAF_9FF5_F6C94DF5EAA3" START WITH 4 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B2B51055_37CB_4B1E_8306_334CDDA5ACD3" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_7171B96C_0A05_4974_9ACC_726263CB64AE" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A359F8E5_E837_4670_A488_6247EFC08A23" START WITH 8 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D854A37B_8520_43C6_823F_9152635C172D" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_18475CD0_1A9A_4A40_A0FF_76E7D414525B" START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE "PUBLIC"."ATOR"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_3D52CACA_5642_4173_A252_ACDE3614828B" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_3D52CACA_5642_4173_A252_ACDE3614828B",
    "DATA_NASCIMENTO" TIMESTAMP,
    "NACIONALIDADE" VARCHAR(255),
    "NOME" VARCHAR(255)
);            
ALTER TABLE "PUBLIC"."ATOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.ATOR;    
INSERT INTO "PUBLIC"."ATOR" VALUES
(1, TIMESTAMP '1996-12-15 21:00:00', 'Americano', 'Lucas Lins');          
CREATE CACHED TABLE "PUBLIC"."CARTAO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_ED57FF39_C934_45C7_A0A7_AFF9F28A7C42" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_ED57FF39_C934_45C7_A0A7_AFF9F28A7C42",
    "CVV" VARCHAR(255),
    "NUMERO" VARCHAR(255),
    "PORTADOR" VARCHAR(255),
    "VALIDADE" VARCHAR(255)
);        
ALTER TABLE "PUBLIC"."CARTAO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CARTAO;  
CREATE CACHED TABLE "PUBLIC"."FILME"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_A359F8E5_E837_4670_A488_6247EFC08A23" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A359F8E5_E837_4670_A488_6247EFC08A23",
    "SINOPSE" VARCHAR(255),
    "TITULO" VARCHAR(255),
    "URL_CAPA" VARCHAR(255),
    "URL_TRAILER" VARCHAR(255),
    "GENERO_ID" INTEGER,
    "VIDEO_ID" INTEGER,
    "ANO_LANCAMENTO" INTEGER
);
ALTER TABLE "PUBLIC"."FILME" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3F" PRIMARY KEY("ID");       
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.FILME;   
INSERT INTO "PUBLIC"."FILME" VALUES
(1, NULL, 'Harry Potter II', NULL, NULL, NULL, NULL, NULL),
(2, NULL, 'Transformers', NULL, NULL, 1, NULL, NULL),
(7, NULL, 'Click', NULL, NULL, 1, NULL, NULL);       
CREATE CACHED TABLE "PUBLIC"."DOCUMENTARIO_ELENCO"(
    "DOCUMENTARIO_ID" INTEGER NOT NULL,
    "ELENCO_ID" INTEGER NOT NULL
);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DOCUMENTARIO_ELENCO;     
CREATE CACHED TABLE "PUBLIC"."EPISODIO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_B2B51055_37CB_4B1E_8306_334CDDA5ACD3" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B2B51055_37CB_4B1E_8306_334CDDA5ACD3",
    "NOME" VARCHAR(255),
    "ID_SERIE_ID" INTEGER,
    "VIDEO_ID" INTEGER
);        
ALTER TABLE "PUBLIC"."EPISODIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EPISODIO;
CREATE CACHED TABLE "PUBLIC"."FAVORITOS"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_DE6CA346_FA89_4A07_8AE5_14FD560FECD1" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DE6CA346_FA89_4A07_8AE5_14FD560FECD1"
);      
ALTER TABLE "PUBLIC"."FAVORITOS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3B" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FAVORITOS;               
CREATE CACHED TABLE "PUBLIC"."FAVORITOS_DOCUMENTARIOS"(
    "FAVORITOS_ID" INTEGER NOT NULL,
    "DOCUMENTARIOS_ID" INTEGER NOT NULL
);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FAVORITOS_DOCUMENTARIOS; 
CREATE CACHED TABLE "PUBLIC"."FAVORITOS_FILMES"(
    "FAVORITOS_ID" INTEGER NOT NULL,
    "FILMES_ID" INTEGER NOT NULL
);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FAVORITOS_FILMES;        
CREATE CACHED TABLE "PUBLIC"."FAVORITOS_SERIES"(
    "FAVORITOS_ID" INTEGER NOT NULL,
    "SERIES_ID" INTEGER NOT NULL
);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FAVORITOS_SERIES;        
CREATE CACHED TABLE "PUBLIC"."FILME_ELENCO"(
    "FILME_ID" INTEGER NOT NULL,
    "ELENCO_ID" INTEGER NOT NULL
);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FILME_ELENCO;            
CREATE CACHED TABLE "PUBLIC"."GENERO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_49DFB9D7_BF09_4F8E_AE8F_A440A2042A8D" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_49DFB9D7_BF09_4F8E_AE8F_A440A2042A8D",
    "DESCRICAO" VARCHAR(255),
    "NOME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."GENERO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7D" PRIMARY KEY("ID");      
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.GENERO;  
INSERT INTO "PUBLIC"."GENERO" VALUES
(1, STRINGDECODE('Filme de com\u00e9dia'), STRINGDECODE('Com\u00e9dia')),
(2, 'Genero pos apocaliptico com zumbis', 'Zombie'),
(3, 'Genero de romance', 'Romance');   
CREATE CACHED TABLE "PUBLIC"."MENSALIDADE"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_E73589DB_09EF_41F0_830D_4F40457B04CA" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_E73589DB_09EF_41F0_830D_4F40457B04CA",
    "DATA_PAGAMENTO" TIMESTAMP,
    "PAGO" BOOLEAN,
    "PLANO_ID" INTEGER,
    "USUARIO_ID" INTEGER
);          
ALTER TABLE "PUBLIC"."MENSALIDADE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MENSALIDADE;             
CREATE CACHED TABLE "PUBLIC"."PLANO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_D854A37B_8520_43C6_823F_9152635C172D" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D854A37B_8520_43C6_823F_9152635C172D",
    "DESCRICAO" VARCHAR(255),
    "NOME" VARCHAR(255),
    "VALOR" FLOAT
);             
ALTER TABLE "PUBLIC"."PLANO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PLANO;   
CREATE CACHED TABLE "PUBLIC"."SERIE_ELENCO"(
    "SERIE_ID" INTEGER NOT NULL,
    "ELENCO_ID" INTEGER NOT NULL
);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SERIE_ELENCO;            
CREATE CACHED TABLE "PUBLIC"."SERIE_EPISODIOS"(
    "SERIE_ID" INTEGER NOT NULL,
    "EPISODIOS_ID" INTEGER NOT NULL
);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SERIE_EPISODIOS;         
CREATE CACHED TABLE "PUBLIC"."VIDEO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_7171B96C_0A05_4974_9ACC_726263CB64AE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_7171B96C_0A05_4974_9ACC_726263CB64AE",
    "DURACAO" INTEGER,
    "THUMBNAIL" VARCHAR(255),
    "TITULO" VARCHAR(255),
    "URL" VARCHAR(255)
);              
ALTER TABLE "PUBLIC"."VIDEO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VIDEO;   
CREATE CACHED TABLE "PUBLIC"."DOCUMENTARIO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_A7A91054_6B19_4EC5_8EA2_269793E320D3" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A7A91054_6B19_4EC5_8EA2_269793E320D3",
    "PRODUTORA" VARCHAR(255),
    "TITULO" VARCHAR(255),
    "URL_CAPA" VARCHAR(255),
    "URL_TRAILER" VARCHAR(255),
    "GENERO_ID" INTEGER,
    "VIDEO_ID" INTEGER,
    "ANO_LANCAMENTO" INTEGER
);       
ALTER TABLE "PUBLIC"."DOCUMENTARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DOCUMENTARIO;            
CREATE CACHED TABLE "PUBLIC"."USUARIO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_18475CD0_1A9A_4A40_A0FF_76E7D414525B" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_18475CD0_1A9A_4A40_A0FF_76E7D414525B",
    "CPF" VARCHAR(255),
    "DATA_NASCIMENTO" TIMESTAMP,
    "EMAIL" VARCHAR(255),
    "ENDERECO" VARCHAR(255),
    "NOME" VARCHAR(255),
    "SENHA" VARCHAR(255),
    "CARTAO_ID" INTEGER,
    "FAVORITOS_ID" INTEGER
);        
ALTER TABLE "PUBLIC"."USUARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO; 
CREATE CACHED TABLE "PUBLIC"."SERIE"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_6EBD83B7_3312_4CAF_9FF5_F6C94DF5EAA3" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6EBD83B7_3312_4CAF_9FF5_F6C94DF5EAA3",
    "NOME" VARCHAR(255),
    "NUMERO_TEMPORADAS" INTEGER,
    "SINOPSE" VARCHAR(255),
    "URL_CAPA" VARCHAR(255),
    "URL_TRAILER" VARCHAR(255),
    "GENERO_ID" INTEGER,
    "ANO_LANCAMENTO" INTEGER
);         
ALTER TABLE "PUBLIC"."SERIE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4B" PRIMARY KEY("ID");       
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.SERIE;   
INSERT INTO "PUBLIC"."SERIE" VALUES
(3, 'The Walking Dead', 11, STRINGDECODE('Baseado na hist\u00f3ria em quadrinhos escrita por Robert Kirkman, este drama potente e visceral retrata a vida nos Estados Unidos p\u00f3s-apocal\u00edptico.'), 'http://127.0.0.1/', 'http://127.0.0.1/', 2, 2010);          
ALTER TABLE "PUBLIC"."FAVORITOS_FILMES" ADD CONSTRAINT "PUBLIC"."UK_EBYLDPP7U99SLIEWD240MCN6R" UNIQUE("FILMES_ID");           
ALTER TABLE "PUBLIC"."FAVORITOS_SERIES" ADD CONSTRAINT "PUBLIC"."UK_Q7SG3WRPKGH5RH37CJAIH2DIC" UNIQUE("SERIES_ID");           
ALTER TABLE "PUBLIC"."DOCUMENTARIO_ELENCO" ADD CONSTRAINT "PUBLIC"."UK_I16LPF40E3FY85Y5O4IOI52PK" UNIQUE("ELENCO_ID");        
ALTER TABLE "PUBLIC"."SERIE_EPISODIOS" ADD CONSTRAINT "PUBLIC"."UK_M08T4C8KWJ2149XDV2F3SEWK3" UNIQUE("EPISODIOS_ID");         
ALTER TABLE "PUBLIC"."FILME_ELENCO" ADD CONSTRAINT "PUBLIC"."UK_9XOAJHJ18U0WJREEVJ64R8A0F" UNIQUE("ELENCO_ID");               
ALTER TABLE "PUBLIC"."FAVORITOS_DOCUMENTARIOS" ADD CONSTRAINT "PUBLIC"."UK_854DM97SUBMRFJ2R5FKVIJ4GU" UNIQUE("DOCUMENTARIOS_ID");             
ALTER TABLE "PUBLIC"."SERIE_ELENCO" ADD CONSTRAINT "PUBLIC"."UK_KX5XAVATX60APV5318XL4LX1K" UNIQUE("ELENCO_ID");               
ALTER TABLE "PUBLIC"."MENSALIDADE" ADD CONSTRAINT "PUBLIC"."FK9WI5E760NYR9HY75OPC3FMXXH" FOREIGN KEY("PLANO_ID") REFERENCES "PUBLIC"."PLANO"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."SERIE" ADD CONSTRAINT "PUBLIC"."FKRJ3C5X4BQW8JK6MKO1ODQNNHT" FOREIGN KEY("GENERO_ID") REFERENCES "PUBLIC"."GENERO"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."FILME" ADD CONSTRAINT "PUBLIC"."FKKHXU1R9LSX3NH21XF0A3QU0KQ" FOREIGN KEY("GENERO_ID") REFERENCES "PUBLIC"."GENERO"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."SERIE_EPISODIOS" ADD CONSTRAINT "PUBLIC"."FKHUHJHUSU18R682F0Q39OK7F0T" FOREIGN KEY("SERIE_ID") REFERENCES "PUBLIC"."SERIE"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."FAVORITOS_FILMES" ADD CONSTRAINT "PUBLIC"."FK5U6Y42KR5GRNI2LX1FR27FY7C" FOREIGN KEY("FILMES_ID") REFERENCES "PUBLIC"."FILME"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."EPISODIO" ADD CONSTRAINT "PUBLIC"."FKAQG2H4BDQEOWVIF62869B5D41" FOREIGN KEY("ID_SERIE_ID") REFERENCES "PUBLIC"."SERIE"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."FILME" ADD CONSTRAINT "PUBLIC"."FKHVGUPE2YOM58MAS80U4F7WKDX" FOREIGN KEY("VIDEO_ID") REFERENCES "PUBLIC"."VIDEO"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."SERIE_EPISODIOS" ADD CONSTRAINT "PUBLIC"."FK1GGORPY9Q32TVU64PVHKORMTW" FOREIGN KEY("EPISODIOS_ID") REFERENCES "PUBLIC"."EPISODIO"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."USUARIO" ADD CONSTRAINT "PUBLIC"."FKS3SL79J5KM6U7H9GBM6QHBUV5" FOREIGN KEY("CARTAO_ID") REFERENCES "PUBLIC"."CARTAO"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."DOCUMENTARIO_ELENCO" ADD CONSTRAINT "PUBLIC"."FKRO88W38C5AC16JY0YNFBCNR34" FOREIGN KEY("DOCUMENTARIO_ID") REFERENCES "PUBLIC"."DOCUMENTARIO"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."FAVORITOS_DOCUMENTARIOS" ADD CONSTRAINT "PUBLIC"."FKL933DTQIUT9TW3C74E9DJANAJ" FOREIGN KEY("DOCUMENTARIOS_ID") REFERENCES "PUBLIC"."DOCUMENTARIO"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."FAVORITOS_SERIES" ADD CONSTRAINT "PUBLIC"."FKK3VRY6KXB2IIH8KYVOA317W4E" FOREIGN KEY("SERIES_ID") REFERENCES "PUBLIC"."SERIE"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."DOCUMENTARIO" ADD CONSTRAINT "PUBLIC"."FK92O3HRKTTHILUT4CDW32BX5WB" FOREIGN KEY("GENERO_ID") REFERENCES "PUBLIC"."GENERO"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."USUARIO" ADD CONSTRAINT "PUBLIC"."FKI4BRP3R7APT9UY0HERFWAC3AT" FOREIGN KEY("FAVORITOS_ID") REFERENCES "PUBLIC"."FAVORITOS"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."SERIE_ELENCO" ADD CONSTRAINT "PUBLIC"."FKOAGWJV7AIHXSSWUQBMMCHC0C6" FOREIGN KEY("ELENCO_ID") REFERENCES "PUBLIC"."ATOR"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."FILME_ELENCO" ADD CONSTRAINT "PUBLIC"."FK3S34WQKLB1MNMT6O4VQDCNO70" FOREIGN KEY("FILME_ID") REFERENCES "PUBLIC"."FILME"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."DOCUMENTARIO" ADD CONSTRAINT "PUBLIC"."FKCCILWDM5KRT3VG5JSS8PISJFT" FOREIGN KEY("VIDEO_ID") REFERENCES "PUBLIC"."VIDEO"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."SERIE_ELENCO" ADD CONSTRAINT "PUBLIC"."FK83LPDSHRNTU2A6KUNNQCVCYG" FOREIGN KEY("SERIE_ID") REFERENCES "PUBLIC"."SERIE"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."FILME_ELENCO" ADD CONSTRAINT "PUBLIC"."FK1YSHQRPAL593BBFE2TFDFQ1ED" FOREIGN KEY("ELENCO_ID") REFERENCES "PUBLIC"."ATOR"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."FAVORITOS_FILMES" ADD CONSTRAINT "PUBLIC"."FKGHL0DPVJ9T1YS9TU00HX3TATA" FOREIGN KEY("FAVORITOS_ID") REFERENCES "PUBLIC"."FAVORITOS"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."FAVORITOS_DOCUMENTARIOS" ADD CONSTRAINT "PUBLIC"."FK4DBAG5YIFC0X9O046TMY60UHU" FOREIGN KEY("FAVORITOS_ID") REFERENCES "PUBLIC"."FAVORITOS"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."MENSALIDADE" ADD CONSTRAINT "PUBLIC"."FKS6WDK6FI3GE7JRL7IYOEU2IO0" FOREIGN KEY("USUARIO_ID") REFERENCES "PUBLIC"."USUARIO"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."FAVORITOS_SERIES" ADD CONSTRAINT "PUBLIC"."FKGEG3IH9TFMAQATYYBD9UR0NUG" FOREIGN KEY("FAVORITOS_ID") REFERENCES "PUBLIC"."FAVORITOS"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."DOCUMENTARIO_ELENCO" ADD CONSTRAINT "PUBLIC"."FKPRVN60MFXY5KXRBB8IQ2U5JGC" FOREIGN KEY("ELENCO_ID") REFERENCES "PUBLIC"."ATOR"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."EPISODIO" ADD CONSTRAINT "PUBLIC"."FK51HP6BFF3WCXVD7AM8RLHL8F6" FOREIGN KEY("VIDEO_ID") REFERENCES "PUBLIC"."VIDEO"("ID") NOCHECK;      
